### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by Master-Antonio** [NodeBB/nodebb-english#22]
https://github.com/NodeBB/nodebb-english/blob/master/installing/os/ubuntu.rst

I have Ubuntu 13.10. 

Problem with this command.
git clone -b v0.6.x https://github.com/NodeBB/NodeBB.git nodebb

There are Error and Warn.
And when after i do .nodebb setup, don't work.

**Comment by julianlam** [comment]
Please post a forum thread about this, as it is probably unrelated to the installation script itself. Thanks! 

https://community.nodebb.org
