### ISSUE TITLE
Openshift install guide pointing to old Redis version

### ISSUE THREAD

**Issue by azariah001** [NodeBB/nodebb-english#53]
I've been trying to configure NodeBB on OpenShift for over 2 weeks now and I cannot get it to stick. I just used this guide NodeBB/nodebb-english/installing/cloud/openshift.rst which the NodeBB forum indicated was up to date so I could have another go and the Redis version is coming up as being to old. I've tried some other Redis cartridge libraries but they either break rhc app ssh while it's logging in or have the same issue. Any ideas?

```
17/8 08:51 [320443] - error: Your Redis version is not new enough to support NodeBB, please upgrade Redis to v2.8.9 or higher.
```

**Comment by redlocal** [comment]
Try using:

http://cartreflect-claytondev.rhcloud.com/reflect?github=transformatordesign/openshift-redis-cart

**Comment by julianlam** [comment]
Defaults to mongo now
