### ISSUE TITLE
Read the Docs broken?

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/nodebb-english#96]
When opening http://docs.nodebb.org I get redirected to http://nodebb.readthedocs.io/projects/nodebb/en/latest/ and this presents a 404 error page of Read the Docs. Something seems to be broken.

**Comment by julianlam** [comment]
Thanks, yes, this seems to be an issue that cropped up yesterday. Will be taking a look today.

**Comment by julianlam** [comment]
Possibly a DNS issue with their changed domain name (readthedocs.io).

**Comment by julianlam** [comment]
[aaaand we're back](http://docs.nodebb.org/en/latest/), though I've also changed the DNS record so `docs.nodebb.org` is a simple `CNAME` instead of proxied via our server first. Hopefully that's fine too.

**Comment by alexschomb** [comment]
Works perfect for me. Thanks for your quick fix! I'm going to close this issue now as it is solved.
